# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-nzam2000"
BBFILE_PATTERN_meta-nzam2000 = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-nzam2000 = "5"

LAYERDEPENDS_meta-nzam2000 = "core"
LAYERSERIES_COMPAT_meta-nzam2000 = "wrynose"
